syntax = "proto3";
package irec;
/**
 * RecoveryRequest представляет собой запрос на восстановление изображение,
 * который приходит от клиента к серверу.
 */
message RecoveryRequest {
    // Изображение, передаваемое в виде массива байт.
    bytes image = 1;

    // Тип передаваемого изображения.
    string mime_type = 2;
}

/**
 * RecoveryResponse - ответ от сервера, который представляет собой
 * восстановленное изображение. Сервер не определяет, как восстановилось
 * изображение, поэтому никакие данные о статусе восстановления не включаются.
 */
message RecoveryResponse {
    // Изображение, передаваемое в виде массива байт.
    bytes image = 1;

    // Тип передаваемого изображения.
    string mime_type = 2;
}

service Irec {
   // Процедура восстановления изображения
   rpc RecoveryImage(RecoveryRequest) returns (RecoveryResponse) {}
}
