name: "unetpp";            # Название модели
backend: "onnxruntime";    # Рантайм для запуска модели
max_batch_size: 8;         # Сколько фотографий будет обрабатываться за раз
version_policy: { all {} } # Какие версии нейросети будут доступны

# Формат входных данных
input [
    {
        name: "input";         # Название входных данных
        data_type: TYPE_FP32;  # Тип входных данных
        dims: [ 3, 256, 256 ]; # Измерения (каналы, высота, ширина)
    }
];

# Формат выходных данных
output [
    {
        name: "output";        # Название выходных данных
        data_type: TYPE_FP32;  # Тип выходных данных
        dims: [ 1, 256, 256 ]; # Измерения (каналы, высота, ширина)
    }
];
